version: "3.9"

services:
  frontend:
    build:
      context: ""
      dockerfile: Dockerfile
    image: "localhost:7002/photo-${IMAGE_TYPE}-frontend:${IMAGE_TAG}"
    container_name: "${CONT_NAME}"
    ports:
      - "${PORT}:4200"